One Hot Encoder using Scikit-Learn

In [22]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [23]:
data = np.array([['Red'], ['Blue'], ['Green']])
encoder = OneHotEncoder()
encoded = encoder.fit_transform(data).toarray().astype('int32')
print(encoded)

[[0 0 1]
 [1 0 0]
 [0 1 0]]


Get feature names (very important)

In [ ]:
features_name = encoder.get_feature_names_out()

Convert to pandas DataFrame

In [25]:
import pandas as pd

encoded_df = pd.DataFrame(encoded, columns=features_name)
encoded_df

x0_Blue  x0_Green  x0_Red
0        0         0       1
1        1         0       0
2        0         1       0

Avoid the Dummy Variable Trap (drop)

In [18]:
encoder = OneHotEncoder(drop='first')
encoded = encoder.fit_transform(data)
print(encoded.toarray())

[[0. 1.]
 [0. 0.]
 [1. 0.]]


Handling unknown categories (REAL-WORLD IMPORTANT)

In [19]:
encoder = OneHotEncoder(handle_unknown='ignore')