In [1]:
import numpy as np

Broadcasting

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
product = arr1*arr2
product

array([ 5, 12, 21, 32])

In [3]:
product.shape

(4,)

In [4]:
product.size

4

Matrix transposing and reshaping

In [ ]:
arr3 = np.arange(6).reshape(2,3) # Reshape the array to (2,3) matrix
print(f"After Reverse: {arr3}")
# arr4 = arr3.transpose() # Transpose the matrix
arr4 = arr3.T 
print(f"After Transpose: {arr4}")

After Reverse: [[0 1 2]
 [3 4 5]]
After Transpose: [[0 3]
 [1 4]
 [2 5]]


Matrix reshapping and flipping

In [15]:
arr5 = np.arange(16).reshape(4,4) # Reshape the array to (4,4) matrix
print(arr5)
arr6 = np.flip(arr5)
print(f"After flipping all axis: {arr6}")
arr7 = np.flip(arr5, axis=1)
print(f"After flipping axis 1: {arr7}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After flipping all axis: [[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
After flipping axis 1: [[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [11]:
arr7 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr7.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Working with mathematical formulas

MSE -> Mean Square Error calculation