In [1]:
import torch
torch.__version__

'2.8.0+cu126'

In [2]:
torch.cuda.is_available()

True

## Scalars, vectors, matrices, and tensors

In [4]:
# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)
tensor0d

tensor(1)

In [8]:
# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])
tensor1d

tensor([1, 2, 3])

In [9]:
# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1,2], [3,4]])
tensor2d

tensor([[1, 2],
        [3, 4]])

In [11]:
# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor3d

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])